name: 'CAR22-HLH'
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.7.0
  - pandas
  - numpy
  - xlrd
  - jupyter
  - scikit-learn
  - seaborn
  - missingno
  - matplotlib
  - snakemake
